import '@/assets/style/globals.css'
import '@/assets/style/index.scss'
import SideBar from '@/components/admin/Sidebar'
import Footer from '@/components/user/Footer'
import Header from '@/components/user/Header'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className='admin-template'>
        <div className='flex'>
          <SideBar />
          <main>
            <div className='col-span-3 flex-1 px-5 pb-10 pt-5'>{children}</div>
          </main>
        </div>
      </body>
    </html>
  )
}
